name: cyruz_124230062_merryhsinaga
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  crypto: ^3.0.3 
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  google_fonts: ^6.1.0
  http: ^1.2.0
  url_launcher: ^6.3.0
  intl: ^0.18.1
  geolocator: ^13.0.1
  google_maps_flutter: ^2.6.0
  flutter_map: ^7.0.0
  latlong2: ^0.9.0
  timezone: ^0.9.2
  flutter_local_notifications: ^17.1.2
  permission_handler: ^11.3.1
  sensors_plus: ^3.1.0
  audioplayers: ^5.2.1
  flutter_cache_manager: ^3.3.1  
  shared_preferences: ^2.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/background.png
    - assets/cyruz.png
  
    - assets/audio/A_major.mp3
    - assets/audio/A_minor.mp3
    - assets/audio/B_major.mp3
    - assets/audio/B_minor.mp3
    - assets/audio/C#_major.mp3
    - assets/audio/C_major.mp3
    - assets/audio/C_minor.mp3
    - assets/audio/D_major.mp3
    - assets/audio/D_minor.mp3
    - assets/audio/E_major.mp3
    - assets/audio/E_minor.mp3
    - assets/audio/F_major.mp3
    - assets/audio/F_minor.mp3
    - assets/audio/G_major.mp3
    - assets/audio/G_minor.mp3
    - assets/audio/C#_minor.mp3
    - assets/audio/D#_major.mp3
    - assets/audio/F#_major.mp3
    - assets/audio/G#_major.mp3
    - assets/audio/G#_minor.mp3

